spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI}

logging:
  level:
    com.bj_food: WARN
    root: ERROR

management:
  tracing:
    sampling:
      probability: 0.1